//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceAndEducation
    {
        public int Id { get; set; }
        public string Education_1st { get; set; }
        public string Education_2st { get; set; }
        public string Education_3st { get; set; }
        public string Technology_1st { get; set; }
        public string Technology_2st { get; set; }
        public string Technology_3st { get; set; }
    }
}
