//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationDetails.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class UserFile
    {
        public int Id { get; set; }

        [Required]
        public string FullName { get; set; }
       
        [EmailAddress]
        [Required]
        [Remote("IsUserEmailAvailable", "ApplyForJob", HttpMethod = "POST", ErrorMessage = "EmailId already exists in database.")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Phone Number Required!")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                     ErrorMessage = "Entered phone format is not valid.")]
        public string MobileNumber { get; set; }
        public string Message { get; set; }
        public string Files { get; set; }
        public Nullable<long> TotalProject { get; set; }
         
        public string ProjectNmae { get; set; }
        public string FilePath { get; set; }

        [Required]
        public string Age { get; set; }
        public string Residence { get; set; }
        public string Address { get; set; }
    }
}
